# Project information
site_name: Aphive Documentation Hub
site_description: Home of all Documentation for Aphive
site_url:

# Copyright
copyright: 'Copyright &copy; 2019 - Present'

# Navigation
nav:
  - Home: index.md
  - Using Cron: using_cron.md
  - Version Control:
    - Intro to Version Control: version_control.md
    - Git: using_git.md
  - Using Homebrew: using_homebrew.md
  - Using SSH Keys: using_ssh_keys.md
  - Using pfSense: using_pfsense.md
  - Upgrade Bash on Mac: upgrade_bash_on_mac.md
  - Apt Sources:
    - Apt: apt.md
    - Debian Sources: debian_sources.md
    - Ubuntu Sources: ubuntu_sources.md
  - MkDocs:
    - Using MkDocs: using-mkdocs.md
    - MkDocs Reference: mkdocs_reference.md
    - MkDocs Message Boxes: message_boxes.md
# <!-- START CUSTOMIZATION SECTION -->
# Documentation and theme
theme:
  logo: 'https://raw.githubusercontent.com/aphive/images/master/ahive-logo.svg'
  favicon: 'https://raw.githubusercontent.com/aphive/images/master/ahive-logo.svg'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  name: 'material'
  palette:
    primary: 'white'
    accent: 'amber'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - javascripts/mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Plugins and Extensions
plugins:
  - search
  - autolinks
  # DO NOT Enable Tags, this is an upcoming feature that I am prepping for. It will break things if you do.
  #- tags:
  #    tags_file: tags.md
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: true
      exclude:
        - index.md
markdown_extensions:
  - codehilite:
      guess_lang: true
      use_pygments: true
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: false
      toc_depth: 4
  - fontawesome_markdown
  - markdown_include.include:
      base_path: .
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.pathconverter
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
# <!-- END CUSTOMIZATION SECTION -->
